name: Bug Report
description: File a bug report.
title: "[Bug]: <title>"
labels: ["bug", "triage"]
assignees:
  - ahmd-sh
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: ALSO tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "The app did not load! I expected the app to load."
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version of SimplyQibla are you running?
      description: You can see it by tapping the info button on the top right of the SimplyQibla app.
      placeholder: ex. 1.1.2
      value: "1.1.2"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What platform(s) are you seeing the problem on?
      multiple: true
      options:
        - Android
        - iOS
        - iPadOS
  - type: textarea
    attributes:
      label: Screenshots
      description: |
        Attach screenshots here if appropriate.
  
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/TowardsIkhlaas/simply_qibla/blob/master/.github/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
